name: iOS Build (Unsigned IPA)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Install CocoaPods (if needed)
        run: |
          cd apps/iOS/MNNLLMChat
          if [ -f "Podfile" ]; then
            pod install
          fi

      - name: Build archive (unsigned)
        run: |
          xcodebuild \
            -project apps/iOS/MNNLLMChat/MNLLMiOS.xcodeproj \
            -scheme MNLLMiOS \
            -configuration Release \
            -sdk iphoneos \
            archive \
            -archivePath build/MNLLMiOS.xcarchive \
            CODE_SIGNING_ALLOWED=NO CODE_SIGN_IDENTITY="" PROVISIONING_PROFILE_SPECIFIER=""

      - name: Create ExportOptions.plist
        run: |
          cat <<EOF > ExportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
          "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>compileBitcode</key>
            <false/>
            <key>method</key>
            <string>ad-hoc</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>stripSwiftSymbols</key>
            <true/>
          </dict>
          </plist>
          EOF

      - name: Export unsigned IPA
        run: |
          xcodebuild \
            -exportArchive \
            -archivePath build/MNLLMiOS.xcarchive \
            -exportPath build/ipa \
            -exportOptionsPlist ExportOptions.plist

      - name: Upload unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: build/ipa/*.ipa
