name: iOS Build (Unsigned IPA)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Create Unsigned IPA
    runs-on: macos-latest

    steps:
      # 第 1 步：检出您的代码仓库
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # 第 2 步：选择一个稳定的 Xcode 版本
      - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'

      # 第 3 步：安装 CocoaPods 依赖
      - name: Cache CocoaPods
        uses: actions/cache@v4
        with:
          path: apps/iOS/MNNLLMChat/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
            
      - name: Install Pods
        run: |
          cd apps/iOS/MNNLLMChat
          pod install

      # 第 4 步：编译和归档 (Archive)
      - name: Archive Project
        run: |
          xcodebuild archive \
            -workspace apps/iOS/MNNLLMChat/MNNLLMChat.xcworkspace \
            -scheme MNNLLMiOS \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath build/MNNLLMChat.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      # 第 5 步：【已修改】手动创建未签名的 IPA
      # 我们不再使用 xcodebuild -exportArchive，而是直接从 .xcarchive 中提取 .app 并打包
      - name: Manually Create Unsigned IPA
        run: |
          # 创建一个用于打包的 Payload 文件夹
          mkdir -p build/ipa/Payload
          
          # 从归档文件中拷贝 .app 到 Payload 文件夹
          cp -R build/MNNLLMChat.xcarchive/Products/Applications/MNLLMiOS.app build/ipa/Payload/
          
          # 进入打包目录
          cd build/ipa
          
          # 将 Payload 文件夹压缩成 IPA 文件
          zip -r MNNLLMChat-unsigned.ipa Payload

      # 第 6 步：上传构建产物 (IPA)
      - name: Upload Unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: MNNLLMChat-unsigned-ipa
          # 注意路径的变化
          path: build/ipa/*.ipa
